version: '2'

services:

  flash_gif_maker:
    build: ./
    image: ouvill/flash_gif_maker
    restart: always
    container_name: flash_gif_maker
    user: "node"
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      NODE_PATH: /home/node/app
      DB_USER: root
      DB_NAME: ${MYSQL_DATABASE}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./:/home/node/app
    ports:
      - 8080:3000
    links:
      - mysql_flash_gif_maker:mysql
    depends_on:
      - mysql_flash_gif_maker
    command: "./entrypoint.sh"

  mysql_flash_gif_maker:
    image: mysql
    container_name: mysql_flash_gif_maker
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /var/docker/mysql_flash_gif_maker:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
